---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bellerophon
  version: "1.18"
  region: eu-central-1

managedNodeGroups:
- name: kubeflow-mng
  desiredCapacity: 3
  instanceType: m5.large
